'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import 'react-toastify/dist/ReactToastify.css';
import { createContext, useEffect, useState } from 'react';
import { ToastContainer } from 'react-toastify';
import { getService } from '@/actions/service';
import Navbar from '@/components/Navbar';
import { getBrandInfo } from '@/actions/brandInfo';
import { getAgreementType } from '@/actions/agreementType';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const onlyNumber = (event) => {
  const allowedKeys = ["Backspace", "Tab", "Escape", "Enter", "Delete", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", ".",];

  if (allowedKeys.includes(event.key)) {
    // Allow key press
    return;
  } else {
    // Block key press
    event.preventDefault();
    return;
  }
}

export const validation = () => {
  // Fetch all the forms we want to apply custom Bootstrap validation styles to
  const forms = document.querySelectorAll('.needs-validation')

  // Loop over them and prevent submission
  Array.from(forms).forEach(form => {
    form.addEventListener('submit', event => {
      if (!form.checkValidity()) {
        event.preventDefault()
        event.stopPropagation()
      }

      form.classList.add('was-validated')
    }, false)
  })
}

export const store = createContext()


export default function RootLayout({ children }) {

  const [data, setData] = useState({})

  useEffect(() => {

    require("bootstrap/dist/js/bootstrap.bundle.min.js");

    const fetchData = async () => {

      const userData = JSON.parse(localStorage.getItem("userData"))

      const service = await getService()

      const brandInfo = await getBrandInfo(userData && userData.brandInfo)

      const agreementType = await getAgreementType()

      setData({ ...data, service, userData, brandInfo, agreementType })
    }

    fetchData()

  }, [])




  return (
    <store.Provider value={[data, setData]}>
      <html lang="en">
        <body className={inter.className}>
          <ToastContainer />
          <Navbar />
          {children}
        </body>
      </html>
    </store.Provider>

  )
}
